### ISSUE TITLE
Module Gradle/Java/CodeQL build fails due to "Unknown javac parameter: --add-opens"

### ISSUE THREAD

**Issue by big-andy-coates** [github/codeql-action#1040]
I have Gradle Java projects that I'd love to use CodeQL to analyse. However, if I enable CodeQL either in its [own workflow][1] or [integrated into the main build workflow][2], then the build fails with error:

```
Error: Exception in thread "main" Unknown javac parameter: --add-opens
	at com.semmle.extractor.java.args.JavaExtractorArgs.parse(JavaExtractorArgs.java:331)
	at com.semmle.extractor.java.JavaExtractor.<init>(JavaExtractor.java:187)
	at com.semmle.extractor.java.JavaExtractor.main(JavaExtractor.java:482)
```

The `--add-opens` command line option is being introduced by the [org.javamodularity.moduleplugin][3] Gradle plugin, which the project is using as its using Java's module system (a.k.a. Jigsaw).

However, its not javac that's complaining about the option, but `com.semmle.extractor.java.args.JavaExtractorArgs.parse`.  The version of java the project is using supports the option. Looks like this could be an issue with the LGTM code...?

[1]: https://github.com/creek-service/creek-base/pull/17
[2]: https://github.com/creek-service/creek-base/pull/16
[3]: https://github.com/java9-modularity/gradle-modules-plugin

**Comment by aeisenberg** [comment]
It looks like you're relying on the autobuilder to trace the build as part of building the database. Can you try commenting out https://github.com/creek-service/creek-base/pull/17/files#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27R55-R56

And then uncomment https://github.com/creek-service/creek-base/pull/17/files#diff-12783128521e452af0cfac94b99b8d250413c516ec71fe6d97dbea666ff7ba27R65-R67 and change it to run the build commands for your specific project?

**Comment by big-andy-coates** [comment]
I've tried both approaches.  See https://github.com/creek-service/creek-base/pull/16...

**Comment by aeisenberg** [comment]
Thanks for letting me know. I heard from the team that supports the java extractor and, unfortunately, it looks like the `add-opens` flag is not supported. I'm waiting for clarification if there is a better workaround, but their current suggestion is to avoid using that option during code scanning.

**Comment by big-andy-coates** [comment]
I'm lucky, in that its the test code that uses the `add-opens` options. So I guess I could just not compile and run the tests.  Would CodeQL be happy with that?

**Comment by yo-h** [comment]
Thanks for filing this issue. This is an oversight in our Java extractor (the `--add-opens` flag is a hidden `javac` option). Our Java team will take a look at fixing this next week.

**Comment by yo-h** [comment]
> So I guess I could just not compile and run the tests. Would CodeQL be happy with that?

I would expect that to work as a short-term workaround.

**Comment by big-andy-coates** [comment]
Thanks @yo-h.

**Comment by big-andy-coates** [comment]
FYI: Changing the build target to `jar` has the build passing: https://github.com/creek-service/creek-base/pull/17

**Comment by aeisenberg** [comment]
Great. I'll close this issue. Feel free to open a new issue if you have any other issues.

**Comment by big-andy-coates** [comment]
@aeisenberg to be fair, the issue isn't resolved. We've just found a work around. May be more useful for others encountering this issue if the issue were left open for now...?

**Comment by aeisenberg** [comment]
Good point. Let's keep this open until a fix is shipped.

**Comment by smowton** [comment]
Hidden options mentioned here: https://github.com/openjdk/jdk/blob/0f2113cee79b9645105b4753c7d7eacb83b872c2/src/jdk.compiler/share/classes/com/sun/tools/javac/main/Option.java

That's for Java 18 - TODO: check if there are hidden options from previous javac versions we need to tolerate as well, and make a PR to update the extractor's list of passed-through options.

Note for the OP: `javac` prints `warning: [options] --add-opens has no effect at compile time`, so you might want to check if your Gradle plugin is doing the right thing there.

**Comment by smowton** [comment]
Fix merged; this should work fine as of CodeQL 2.9.1

**Comment by big-andy-coates** [comment]
@smowton when will 2.9.1 go live?  Is there somewhere I can view this?

I see that 2.9.1 has has been build, but trying a full build still fails with the same error. (See https://github.com/creek-service/creek-test/pull/38)

**Comment by edoardopirovano** [comment]
It typically around two weeks for new CodeQL releases to make it into the cache we use to avoid downloading a release every time a workflow is run. You could add `tools: latest` to the parameters passed to the `init` step of your workflow if you would like to make sure it uses 2.9.1 now. This will add around a minute to your workflow's duration but will ensure you always have the latest version without the couple of weeks delay for it to get into the cache.

**Comment by edoardopirovano** [comment]
I'll also note that even with the above, you won't get 2.9.1 just yet because we haven't yet bumped `latest` to point to 2.9.1 as it is very new. That's due to happen on Monday, or Tuesday at the latest, assuming we don't uncover any issues with it.

**Comment by smowton** [comment]
If you wanted to try it out locally, there's a build of the CLI at https://github.com/github/codeql-cli-binaries/releases/tag/v2.9.1

**Comment by big-andy-coates** [comment]
All deployed and working now. Thanks all.
